version: '2'

volumes:
  esdata:
  mysqldata:
  geodata:
  app:

services:
  web:
    image: encoreptl/thermostat-web
    restart: unless-stopped
    volumes:
      - app:/thermostat
    depends_on:
      - app
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    links:
      - app
    ports:
      - '80:80'

  app:
    image: encoreptl/thermostat-app
    build: .
    restart: unless-stopped
    links:
      - mysql:mysql
      - elasticsearch:elasticsearch
    volumes:
      - app:/thermostat
    depends_on:
      - mysql
      - elasticsearch

  mysql:
    image: mysql:5.7.20
    restart: unless-stopped
    volumes:
      - mysqldata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.3
    container_name: elasticsearch
    restart: unless-stopped
    environment:
      - cluster.name=thermostat-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    volumes:
      - esdata:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:5.6.3
    restart: unless-stopped
    environment:
      SERVER_NAME: localhost
    depends_on:
      - elasticsearch
    links:
      - elasticsearch:elasticsearch
    ports:
      - 5601:5601

  geoserver:
    image: kartoza/geoserver
    restart: unless-stopped
    ports:
      - '8080:8080'
    volumes:
      - geodata:/opt/geoserver/data_dir
