default: &default
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  username: <%= Rails.application.secrets[:database][:username] %>
  password: <%= Rails.application.secrets[:database][:password] %>
  host: <%= Rails.application.secrets[:database][:host] %>
  database: <%= Rails.application.secrets[:database][:name] %>

development: *default
test: *default
production: *default
