production:
  secret_key_base: 247799114f6186d106a18cddc675758c6fdf85c2b72dac90dd807d4920d8b2c0316fa4b5b44e586522eded653d989abd15d20721b6717b52a8d531a28baae83a
  database:
    :host: mysql
    :name: thermostat_production
    :username: root
    :password: root
  email_username: <%= ENV["EMAIL_USERNAME"] %>
  email_password: <%= ENV["EMAIL_PASSWORD"] %>
  elastic_host: elasticsearch
  elastic_user: elastic
  elastic_password: changeme
